name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    env:
      PYTHONWARNINGS: "ignore"  # Optional to suppress warnings

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install browser drivers
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver firefox-geckodriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true
        sudo ln -s /usr/bin/geckodriver /usr/local/bin/geckodriver || true

    - name: Run tests on ${{ matrix.browser }}
      run: |
        pytest -n auto --browser=${{ matrix.browser }}
